# Generated by Django 4.1.7 on 2023-04-05 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_app_currency', models.IntegerField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('purchases', models.ManyToManyField(blank=True, related_name='currency_package_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
