# Generated by Django 4.1.7 on 2023-04-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_currency', '0002_currencytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencytransaction',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='currencytransaction',
            name='card_exp_month',
        ),
        migrations.RemoveField(
            model_name='currencytransaction',
            name='card_exp_year',
        ),
        migrations.RemoveField(
            model_name='currencytransaction',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='currencytransaction',
            name='country',
        ),
        migrations.RemoveField(
            model_name='currencytransaction',
            name='payment_method',
        ),
    ]
