# Generated by Django 4.1.7 on 2023-04-09 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_currency', '0004_alter_currencytransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypackage',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='currency_package_purchases', related_query_name='currency_package_purchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
