# Generated by Django 4.1.7 on 2023-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_currency', '0007_currencypackage_og_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypackage',
            name='og_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencypackage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
