# Generated by Django 4.1.7 on 2023-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_currency', '0008_alter_currencypackage_og_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypackage',
            name='stripe_price',
            field=models.IntegerField(blank=True),
        ),
    ]
