# Generated by Django 4.1.7 on 2023-04-03 09:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('profile_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('note', models.TextField(blank=True, null=True)),
                ('search_document', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['first_name', 'last_name'], name='account_add_first_n_26ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address'], name='account_add_address_5a0478_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='account_add_city_2397e1_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='account_add_state_c8aad9_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='account_add_country_5c0253_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='account_add_postal__fe077a_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='account_cus_usernam_9f698e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='account_cus_email_5f481e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='account_cus_phone_n_bc0a85_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['country'], name='account_cus_country_0fa158_idx'),
        ),
    ]
