# Generated by Django 4.1.7 on 2023-05-05 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('event_type', models.CharField(choices=[('ACCOUNT_CREATED', 'account_created'), ('ACCOUNT_ACTIVATED', 'account_activated'), ('ACCOUNT_DEACTIVATED', 'account_deactivated'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED', 'phone_changed'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED', 'email_changed'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent'), ('CUSTOMER_DELETED', 'customer_deleted'), ('NAME_ASSIGNED', 'name_assigned'), ('EMAIL_ASSIGNED', 'email_assigned'), ('PHONE_ASSIGNED', 'phone_assigned'), ('NOTE_ADDED', 'note_added'), ('CURRENCY_WITHDRAWN', 'currency_withdrawn'), ('CURRENCY_DEPOSITED', 'currency_deposited'), ('PLACED_SINGLE_ORDER', 'placed_single_order'), ('PLACED_BUNDLE_ORDER', 'placed_bundle_order'), ('PLACED_TOPUP_ORDER', 'placed_topup_order'), ('CREATED_AUCTION', 'created_auction'), ('DELETED_AUCTION', 'deleted_auction'), ('PLACED_AUCTION_BID', 'placed_auction_bid'), ('RECEIVED_AUCTION_BID', 'received_auction_bid'), ('WATCHED_ADS_IN_PLATFORM', 'watched_ads_in_platform'), ('USED_PROMO_CODE', 'used_promo_code')], max_length=255, verbose_name='Event type')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Event parameters')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
