# Generated by Django 4.1.7 on 2023-05-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230505_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerevent',
            options={'ordering': ('date',)},
        ),
    ]
