# Generated by Django 4.1.7 on 2023-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevent',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'account_created'), ('ACCOUNT_ACTIVATED', 'account_activated'), ('ACCOUNT_DEACTIVATED', 'account_deactivated'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('PASSWORD_CHANGED', 'password_changed'), ('PHONE_CHANGE_REQUEST', 'phone_change_request'), ('PHONE_CHANGED', 'phone_changed'), ('EMAIL_CHANGE_REQUEST', 'email_change_request'), ('EMAIL_CHANGED', 'email_changed'), ('VERIFICATION_EMAIL_SENT', 'verification_email_sent'), ('CUSTOMER_DELETED', 'customer_deleted'), ('NAME_ASSIGNED', 'name_assigned'), ('EMAIL_ASSIGNED', 'email_assigned'), ('PHONE_ASSIGNED', 'phone_assigned'), ('NOTE_ADDED', 'note_added'), ('CURRENCY_WITHDRAWN', 'currency_withdrawn'), ('CURRENCY_DEPOSITED', 'currency_deposited'), ('PLACED_SINGLE_ORDER', 'placed_single_order'), ('PLACED_BUNDLE_ORDER', 'placed_bundle_order'), ('PLACED_TOPUP_ORDER', 'placed_topup_order'), ('CREATED_AUCTION', 'created_auction'), ('DELETED_AUCTION', 'deleted_auction'), ('WATCHED_ADS_IN_PLATFORM', 'watched_ads_in_platform'), ('USED_PROMO_CODE', 'used_promo_code')], max_length=255, verbose_name='Event type'),
        ),
    ]
