# Generated by Django 4.1.7 on 2023-05-14 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customerevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CheckInHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_window', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
