# Generated by Django 4.1.7 on 2023-04-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playercard', '0006_remove_playercard_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('bundle_price', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(to='playercard.playercard')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playercard.cardrarity')),
            ],
        ),
    ]
