# Generated by Django 4.1.7 on 2023-04-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbundle',
            name='cardbundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_bundle', to='bundle.cardbundle'),
        ),
    ]
