# Generated by Django 4.1.7 on 2023-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0006_remove_playercard_collection'),
        ('bundle', '0002_cardbundle_cardbundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbundle',
            name='cardbundle',
        ),
        migrations.AlterField(
            model_name='cardbundle',
            name='cards',
            field=models.ManyToManyField(related_name='card_in_bundles', to='playercard.playercard'),
        ),
    ]
