# Generated by Django 4.1.7 on 2023-04-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0008_remove_playercard_cardbundle'),
        ('bundle', '0003_remove_cardbundle_cardbundle_alter_cardbundle_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('bundle_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BundleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('card_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundle.bundle')),
                ('player_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playercard.playercard')),
            ],
            options={
                'unique_together': {('card_bundle', 'player_card')},
            },
        ),
        migrations.DeleteModel(
            name='CardBundle',
        ),
        migrations.AddField(
            model_name='bundle',
            name='cards',
            field=models.ManyToManyField(through='bundle.BundleCard', to='playercard.playercard'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playercard.cardrarity'),
        ),
    ]
