# Generated by Django 4.1.7 on 2023-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0008_remove_playercard_cardbundle'),
        ('bundle', '0004_bundle_bundlecard_delete_cardbundle_bundle_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='cards',
            field=models.ManyToManyField(limit_choices_to={'owner': None}, through='bundle.BundleCard', to='playercard.playercard'),
        ),
    ]
