# Generated by Django 4.1.7 on 2023-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0005_alter_bundle_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='bundle_covers/'),
        ),
    ]
