# Generated by Django 4.1.7 on 2023-04-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0006_bundle_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='bundle_price',
            new_name='price',
        ),
    ]
