# Generated by Django 4.1.7 on 2023-04-18 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bundle', '0007_rename_bundle_price_bundle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='sold_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
