# Generated by Django 4.1.7 on 2023-05-13 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0009_alter_bundle_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
