# Generated by Django 4.1.7 on 2023-05-13 22:52

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Bundle = apps.get_model('bundle', 'Bundle')
    for bundle in Bundle.objects.all():
        bundle.uuid = uuid.uuid4()
        bundle.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0010_bundle_uuid'),
    ]

    operations = [
                migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),

    ]
