# Generated by Django 4.1.7 on 2023-05-13 22:52

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0011_auto_20230513_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
