# Generated by Django 4.1.7 on 2023-04-07 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_team_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playercard', '0006_remove_playercard_collection'),
        ('collection', '0002_collectionreward_cardcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTeamCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_master', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(related_name='master_team_collection', to='playercard.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='MasterTeamPositionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_master', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(related_name='master_team_position_collection', to='playercard.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPositionCollectionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.masterteampositioncollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeamCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_master', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(related_name='user_team_collection', to='playercard.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeamPositionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_master', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(related_name='user_team_position_collection', to='playercard.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CollectionReward',
            new_name='TeamCollectionReward',
        ),
        migrations.DeleteModel(
            name='CardCollection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AlterField(
            model_name='teamcollectionreward',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.masterteamcollection'),
        ),
    ]
