# Generated by Django 4.1.7 on 2023-04-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_teamcollectionreward_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterteamcollection',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='masterteamcollection',
            name='team',
        ),
        migrations.RemoveField(
            model_name='masterteampositioncollection',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='masterteampositioncollection',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamCollectionReward',
        ),
        migrations.DeleteModel(
            name='TeamPositionCollectionReward',
        ),
        migrations.RemoveField(
            model_name='userteamcollection',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='userteamcollection',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userteamcollection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userteampositioncollection',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='userteampositioncollection',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userteampositioncollection',
            name='user',
        ),
        migrations.DeleteModel(
            name='MasterTeamCollection',
        ),
        migrations.DeleteModel(
            name='MasterTeamPositionCollection',
        ),
        migrations.DeleteModel(
            name='UserTeamCollection',
        ),
        migrations.DeleteModel(
            name='UserTeamPositionCollection',
        ),
    ]
