# Generated by Django 4.1.7 on 2023-04-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playercard', '0009_alter_playercard_owner_alter_playercard_player_and_more'),
        ('base', '0004_alter_team_options_alter_team_unique_together'),
        ('collection', '0005_remove_masterteamcollection_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward', models.PositiveIntegerField(default=100000, help_text='Reward in DJOBA coins')),
                ('is_active', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(to='playercard.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.team')),
            ],
        ),
    ]
