# Generated by Django 4.1.7 on 2023-04-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
        ('collection', '0007_alter_collection_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.reward'),
        ),
    ]
