# Generated by Django 4.1.7 on 2023-04-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0011_alter_playercard_player'),
        ('collection', '0009_alter_collection_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playercard.cardrarity'),
        ),
    ]
