# Generated by Django 4.1.7 on 2023-04-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_rename_reward_in_coins_djobareward_amount'),
        ('playercard', '0013_rename_locked_playercard_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0010_collection_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(related_name='collections', to='playercard.playercard'),
        ),
        migrations.CreateModel(
            name='CompletedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_received', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.djobareward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'collection')},
            },
        ),
    ]
