# Generated by Django 4.1.7 on 2023-04-24 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)]),
        ),
    ]
