# Generated by Django 4.1.7 on 2023-04-24 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0002_alter_auction_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchers',
            field=models.ManyToManyField(related_name='watched_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
