# Generated by Django 4.1.7 on 2023-04-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0013_rename_locked_playercard_is_locked'),
        ('auction', '0004_auction_auction_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playercard.playercard'),
        ),
    ]
