# Generated by Django 4.1.7 on 2023-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_auction_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddConstraint(
            model_name='auction',
            constraint=models.UniqueConstraint(fields=('card', 'owner'), name='unique_auction'),
        ),
    ]
