# Generated by Django 4.1.7 on 2023-05-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_auction_options_auction_unique_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
