# Generated by Django 4.1.7 on 2023-05-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_remove_auction_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
