# Generated by Django 4.1.7 on 2023-05-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auction_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
