# Generated by Django 4.1.7 on 2023-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auction_sold'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auction',
            name='unique_auction',
        ),
        migrations.AddConstraint(
            model_name='auction',
            constraint=models.UniqueConstraint(fields=('card', 'owner', 'start_time'), name='unique_auction'),
        ),
    ]
