# Generated by Django 4.1.7 on 2023-06-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
