# Generated by Django 4.1.7 on 2023-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_currency_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('card_purchase', 'Card Purchase'), ('bundle_purchase', 'Bundle Purchase'), ('currency_purchase', 'Currency Purchase')], max_length=50),
        ),
    ]
