# Generated by Django 4.1.7 on 2023-04-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0005_auctiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontransaction',
            name='number_of_bids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctiontransaction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctiontransaction',
            name='winning_bid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
