# Generated by Django 4.1.7 on 2023-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auctiontransaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Card Purchase', 'card_purchase'), ('Bundle Purchase', 'bundle_purchase')], max_length=50),
        ),
    ]
