# Generated by Django 4.1.7 on 2023-06-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('card_purchase', 'Card Purchase'), ('bundle_purchase', 'Bundle Purchase')], max_length=50),
        ),
    ]
