# Generated by Django 4.1.7 on 2023-04-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractemail',
            name='body_html',
        ),
    ]
