# Generated by Django 4.1.7 on 2023-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_player_jersey_number_alter_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['year'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'country', 'year')},
        ),
    ]
