# Generated by Django 4.1.7 on 2023-05-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_team_options_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('country', 'year')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
