# Generated by Django 4.1.7 on 2023-04-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playercard', '0009_alter_playercard_owner_alter_playercard_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('card', 'Card'), ('coins', 'Coins')], default='coins', max_length=10)),
                ('reward_in_coins', models.PositiveIntegerField(default=100000, help_text='Reward in DJOBA coins')),
                ('is_active', models.BooleanField(default=True)),
                ('reward_in_cards', models.ManyToManyField(blank=True, help_text='Reward in cards', to='playercard.playercard')),
            ],
        ),
    ]
