# Generated by Django 4.1.7 on 2023-04-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJOBAReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_in_coins', models.PositiveIntegerField(default=500000, help_text='Reward in DJOBA coins')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_in_cards',
        ),
    ]
