# Generated by Django 4.1.7 on 2023-04-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_djobareward_remove_reward_reward_in_cards'),
        ('collection', '0009_alter_collection_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
