# Generated by Django 4.1.7 on 2023-04-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_delete_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djobareward',
            old_name='reward_in_coins',
            new_name='amount',
        ),
    ]
