# Generated by Django 4.1.7 on 2023-04-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Rarity',
                'verbose_name_plural': 'Rarities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_sale', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Show this playercard in search results and portfolios.', verbose_name='Is public')),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/playercards')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('number_likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.player')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playercard.cardrarity')),
            ],
            options={
                'verbose_name': 'Playercard',
                'verbose_name_plural': 'Playercards',
                'ordering': ['player'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCardLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playercard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playercard.playercard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='playercard',
            index=models.Index(fields=['owner'], name='playercard__owner_i_000b31_idx'),
        ),
        migrations.AddIndex(
            model_name='playercard',
            index=models.Index(fields=['player'], name='playercard__player__fc6db4_idx'),
        ),
        migrations.AddIndex(
            model_name='playercard',
            index=models.Index(fields=['rarity'], name='playercard__rarity__078b42_idx'),
        ),
    ]
