# Generated by Django 4.1.7 on 2023-04-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('playercard', '0002_alter_cardrarity_options_alter_playercard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playercard.playercard')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_collection', to='collection.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_collection_user', to='playercard.playercard')),
            ],
        ),
    ]
