# Generated by Django 4.1.7 on 2023-04-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0004_alter_cardcollection_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardCollection',
        ),
    ]
