# Generated by Django 4.1.7 on 2023-04-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0005_delete_cardcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercard',
            name='collection',
        ),
    ]
