# Generated by Django 4.1.7 on 2023-04-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0003_remove_cardbundle_cardbundle_alter_cardbundle_cards'),
        ('playercard', '0006_remove_playercard_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='cardbundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_container', to='bundle.cardbundle'),
        ),
    ]
