# Generated by Django 4.1.7 on 2023-04-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0007_playercard_cardbundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercard',
            name='cardbundle',
        ),
    ]
