# Generated by Django 4.1.7 on 2023-04-09 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_team_options_alter_team_unique_together'),
        ('playercard', '0008_remove_playercard_cardbundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='base.player'),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playercard',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='playercard.cardrarity'),
        ),
        migrations.AlterField(
            model_name='playercardlike',
            name='playercard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='playercard.playercard'),
        ),
        migrations.AlterField(
            model_name='playercardlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
