# Generated by Django 4.1.7 on 2023-04-23 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playercard', '0009_alter_playercard_owner_alter_playercard_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playercards', to=settings.AUTH_USER_MODEL),
        ),
    ]
