# Generated by Django 4.1.7 on 2023-04-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_team_options_alter_team_unique_together'),
        ('playercard', '0010_alter_playercard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playercards', to='base.player'),
        ),
    ]
