# Generated by Django 4.1.7 on 2023-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0011_alter_playercard_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
