# Generated by Django 4.1.7 on 2023-04-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0012_playercard_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='locked',
            new_name='is_locked',
        ),
    ]
