# Generated by Django 4.1.7 on 2023-06-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0014_playercard_edition_alter_playercard_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercard',
            old_name='edition',
            new_name='season',
        ),
    ]
