# Generated by Django 4.1.7 on 2023-06-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0015_rename_edition_playercard_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='edition',
            field=models.CharField(default='AFCON LEGENDS', max_length=255),
        ),
    ]
